-- ============================================================
-- TOOLORA — Supabase Database Schema
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- PROFILES (extends auth.users)
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  plan TEXT NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'pro', 'unlimited')),
  stripe_customer_id TEXT UNIQUE,
  razorpay_customer_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- RLS: Users can read/update their own profile
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Service role can do everything (for admin client)
CREATE POLICY "Service role full access to profiles" ON profiles
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ============================================================
-- USAGE LOGS (rate limiting + analytics)
-- ============================================================
CREATE TABLE IF NOT EXISTS usage_logs (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  ip TEXT,
  tool_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Index for fast rate limit queries
CREATE INDEX IF NOT EXISTS idx_usage_logs_user_created ON usage_logs(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_usage_logs_ip_created ON usage_logs(ip, created_at) WHERE user_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_usage_logs_tool ON usage_logs(tool_name);

-- RLS: Service role only (rate limiting done server-side with admin client)
ALTER TABLE usage_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access to usage_logs" ON usage_logs
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ============================================================
-- SUBSCRIPTIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS subscriptions (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE UNIQUE NOT NULL,
  plan TEXT NOT NULL CHECK (plan IN ('pro', 'unlimited')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'cancelled', 'expired', 'past_due')),
  stripe_subscription_id TEXT UNIQUE,
  razorpay_subscription_id TEXT,
  current_period_end TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own subscription" ON subscriptions
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Service role full access to subscriptions" ON subscriptions
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ============================================================
-- BLOG POSTS (SEO content — generated by AI agents)
-- ============================================================
CREATE TABLE IF NOT EXISTS blog_posts (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  content TEXT NOT NULL,
  meta_description TEXT,
  tags TEXT[] DEFAULT '{}',
  read_time INTEGER DEFAULT 5,
  published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published ON blog_posts(published, created_at DESC);

-- Public read access for published posts
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read published blog posts" ON blog_posts
  FOR SELECT USING (published = TRUE);

CREATE POLICY "Service role full access to blog_posts" ON blog_posts
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ============================================================
-- NEWSLETTER SUBSCRIBERS
-- ============================================================
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  subscribed BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access to newsletter_subscribers" ON newsletter_subscribers
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ============================================================
-- MAINTENANCE LOGS (agent activity log)
-- ============================================================
CREATE TABLE IF NOT EXISTS maintenance_logs (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  status TEXT NOT NULL,
  checks JSONB,
  actions TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE maintenance_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access to maintenance_logs" ON maintenance_logs
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ============================================================
-- CRON LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS cron_logs (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  job TEXT NOT NULL,
  status TEXT NOT NULL,
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE cron_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access to cron_logs" ON cron_logs
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ============================================================
-- TRIGGERS: Auto-create profile on signup
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, plan)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    'free'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- TRIGGERS: Auto-update updated_at timestamps
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER subscriptions_updated_at BEFORE UPDATE ON subscriptions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER blog_posts_updated_at BEFORE UPDATE ON blog_posts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- SEED: Insert sample blog posts so blog isn't empty at launch
-- ============================================================
INSERT INTO blog_posts (title, slug, content, meta_description, tags, read_time, published)
VALUES
(
  'How to Summarize a PDF with AI in Under 30 Seconds',
  'how-to-summarize-pdf-with-ai',
  '<p>Reading lengthy research papers, annual reports, or legal documents takes hours. With AI, you can extract the key insights from any PDF in under 30 seconds — for free.</p>
  <h2>Why PDF Summarization Matters</h2>
  <p>The average professional reads 50+ documents per month. At 20 minutes per document, that''s 16+ hours — two full workdays — lost to reading. AI summarization cuts this to minutes.</p>
  <h2>How to Use Toolora''s Free PDF Summarizer</h2>
  <ol>
  <li>Go to <a href="/tools/pdf-summarizer">Toolora PDF Summarizer</a></li>
  <li>Upload your PDF (up to 10 MB, no signup required)</li>
  <li>Choose summary length: Short, Medium, or Detailed</li>
  <li>Click "Summarize PDF" and get results in under 15 seconds</li>
  </ol>
  <h2>What Makes AI Summarization Better Than Manual Reading?</h2>
  <p>Our AI uses LLaMA 3.1 70B — one of the most capable AI models — to extract key arguments, findings, statistics, and conclusions. It understands context, not just keywords.</p>
  <p>Try it free today at <a href="/tools/pdf-summarizer">toolora.com/tools/pdf-summarizer</a> — no credit card, no signup needed.</p>',
  'Learn how to summarize any PDF in seconds using free AI. No signup needed. Powered by LLaMA 3 — extract key insights from research papers, reports & more.',
  ARRAY['pdf', 'ai tools', 'productivity'],
  5,
  TRUE
),
(
  'Best Free AI Grammar Checker in 2024 (No Signup Required)',
  'best-free-ai-grammar-checker-2024',
  '<p>Finding a truly free grammar checker that doesn''t require signup, watermarks, or paywalls is hard. We''ve built one — and it''s better than most paid tools.</p>
  <h2>What Makes Toolora''s Grammar Checker Different?</h2>
  <p>Most grammar checkers use simple rule-based systems. Toolora uses LLaMA 3.1 70B — a large language model that understands context, meaning, and style — not just grammar rules.</p>
  <h2>Features</h2>
  <ul>
  <li>Grammar and spelling error detection</li>
  <li>Style improvement suggestions</li>
  <li>Explanation for every correction</li>
  <li>Grammar score (0-100)</li>
  <li>No signup required for 5 daily uses</li>
  </ul>
  <h2>How to Use It</h2>
  <p>Visit <a href="/tools/grammar-checker">Toolora Grammar Checker</a>, paste your text, and click check. You''ll see your corrected text and a list of every error with explanations.</p>
  <p>Start checking your writing for free at <a href="/tools/grammar-checker">toolora.com/tools/grammar-checker</a>.</p>',
  'Best free AI grammar checker with no signup. Fix grammar, spelling and style instantly. Powered by LLaMA 3 — better than Grammarly for basic use.',
  ARRAY['grammar', 'writing', 'tools'],
  6,
  TRUE
)
ON CONFLICT (slug) DO NOTHING;
