import type { Metadata } from 'next';
import { ToolSchemas } from '@/components/shared/ToolSchemas';

export const metadata: Metadata = {
  title: 'Free QR Code Generator — Create QR Codes Online Instantly | Formly',
  description: 'Generate QR codes for free online — URLs, text, WiFi credentials, contact cards (vCard), and email. Download as PNG or SVG. No signup required.',
  keywords: ['qr code generator free', 'create qr code online', 'qr code maker', 'free qr code creator', 'url to qr code', 'wifi qr code generator', 'vcard qr code', 'qr code png download', 'custom qr code free', 'qr code generator no signup'],
  openGraph: { title: 'Free QR Code Generator | Formly', description: 'Generate QR codes for URLs, text, WiFi, vCards — download as PNG or SVG. Free, no signup.', url: 'https://formly.tools/tools/qr-code', type: 'website', siteName: 'Formly' },
  twitter: { card: 'summary_large_image', title: 'Free QR Code Generator | Formly', description: 'Create QR codes for URLs, WiFi, contact cards & more. Download PNG or SVG instantly.' },
  alternates: { canonical: 'https://formly.tools/tools/qr-code' },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <ToolSchemas
        name="QR Code Generator"
        description="Free online QR code generator that creates QR codes for URLs, plain text, WiFi credentials, vCard contact cards, and email addresses. Download as PNG or SVG."
        url="https://formly.tools/tools/qr-code"
        category="UtilitiesApplication"
        features={['Generate QR codes for URLs, text, WiFi & vCards', 'Download as PNG or SVG', 'Customizable size and error correction', 'No signup required', 'Works entirely in-browser']}
        faqs={[
          { q: "Is the QR code generator free to use?", a: "Yes — the QR Code Generator is completely free with no limits. Generate unlimited QR codes for URLs, text, WiFi credentials, contact cards, and email addresses without signing up." },
          { q: "What types of QR codes can I create?", a: "You can create QR codes for: website URLs, plain text, WiFi network credentials (SSID + password), vCard contact cards (name, phone, email), and email addresses." },
          { q: "Can I download the QR code as an image?", a: "Yes — download your QR code as a PNG image (for web, print, presentations) or SVG (for scalable, print-quality use). Both formats are free." },
          { q: "How accurate are the QR codes?", a: "Formly generates standard QR codes using the QR Code specification, compatible with all modern smartphones and QR readers. Error correction is built in to ensure readability even if the code is partially damaged." },
          { q: "Do generated QR codes expire?", a: "QR codes generated by Formly are static — they work as long as the destination URL or content exists. They do not expire, unlike dynamic QR codes from paid services." },
        ]}
        steps={[
          { name: 'Select content type', text: 'Choose what your QR code should contain: URL, text, WiFi, vCard, or email.' },
          { name: 'Enter your content', text: 'Type or paste the URL, WiFi password, contact details, or text you want to encode.' },
          { name: 'Download QR code', text: 'Click Download to save your QR code as a PNG or SVG file, ready to use anywhere.' },
        ]}
      />
      {children}
    </>
  );
}
