'use client';

import { useState } from 'react';
import { ChevronDown } from 'lucide-react';

const FAQS = [
  {
    q: 'Is Formly really free? What are the limits?',
    a: 'Yes! You get 5 free AI requests per day across all tools — no credit card, no signup needed. Free accounts (with signup) get 10/day. Pro users get 200/day and Unlimited users get, well, unlimited.',
  },
  {
    q: 'What AI model powers Formly?',
    a: "We use Groq's blazing-fast AI infrastructure — delivering high-quality output comparable to GPT-4 for most tasks, completely free.",
  },
  {
    q: 'Is my data safe? Do you store my content?',
    a: 'Your privacy is our priority. We do NOT store the content you process through our tools. Inputs are sent directly to the AI, output returned to you, and nothing is saved. We only store usage counts for rate limiting.',
  },
  {
    q: 'Can I cancel my subscription anytime?',
    a: "Yes, absolutely. Cancel anytime from your dashboard in one click. You'll keep access until the end of the billing period. We offer a 7-day money-back guarantee, no questions asked.",
  },
  {
    q: 'Do you support Indian payment methods?',
    a: 'Yes! We accept UPI, Debit/Credit cards, Net Banking, Apple Pay, Google Pay, and all major wallets — via DodoPayments. Your local currency (USD, EUR, INR, etc.) is shown automatically at checkout. All taxes included.',
  },
  {
    q: 'How accurate are the AI outputs?',
    a: 'Groq AI produces excellent output for most tasks. For grammar checking, paraphrasing, summarization, and email writing, quality is comparable to premium tools like Grammarly or Jasper — at a fraction of the price.',
  },
  {
    q: 'Is there an API available?',
    a: "API access is coming soon for Unlimited plan subscribers. You'll be able to integrate Formly's AI tools into your own applications. Join the waitlist via your dashboard.",
  },
  {
    q: 'What languages are supported?',
    a: 'Formly works best in English but also supports Spanish, French, German, Italian, Portuguese, Hindi, and Arabic for most tasks.',
  },
  {
    q: 'What tools does Formly offer for free?',
    a: 'Formly offers 26 free AI-powered and utility tools, including a PDF summarizer, paraphraser, grammar checker, AI email writer, pay stub generator, resume builder, contract generator, JSON formatter, base64 encoder, regex tester, diff checker, PDF-to-Markdown converter, expense splitter, loan/EMI calculator, word counter, and more. All tools are accessible without an account.',
  },
  {
    q: 'Can I use Formly tools without creating an account?',
    a: 'Yes. Every tool on Formly works without creating an account. Anonymous visitors get 5 free AI requests per day. Signing up for a free account raises that to 10/day — still no credit card required.',
  },
  {
    q: 'How accurate is the AI pay stub generator?',
    a: 'The AI pay stub generator produces professional, realistic pay stubs based on the information you provide. It calculates federal and state tax withholdings, FICA (Social Security and Medicare), and net pay automatically. Always review the output and consult a payroll professional for official payroll processing.',
  },
  {
    q: "What's the difference between Formly's free and Pro plan?",
    a: "The free plan gives you 5–10 AI requests per day with no signup required. The Pro plan ($9.99/month) gives you 200 AI requests per day, priority processing, and access to all premium features. The Unlimited plan removes all daily limits. Both paid plans include a 7-day money-back guarantee.",
  },
  {
    q: 'Can I export documents as PDF from Formly?',
    a: 'Yes. Tools like the resume builder, pay stub generator, and contract generator let you download your finished document as a polished PDF. The PDF export is available on both free and Pro plans.',
  },
  {
    q: 'Does Formly work with all browsers?',
    a: 'Formly works in all modern browsers — Chrome, Firefox, Safari, Edge, and Brave — on both desktop and mobile. No browser extension or plugin is required.',
  },
  {
    q: "Is Formly's contract generator legally binding?",
    a: "The contracts generated by Formly are based on standard legal templates and are designed to be legally sound. However, they become binding only when all parties sign them. For high-value or complex agreements, we recommend having a licensed attorney review the document before signing.",
  },
  {
    q: 'How does Formly protect my data?',
    a: 'Formly does not store the content you submit to any tool. Your text, documents, and form inputs are processed in real time and never saved to our servers. Account data (email, usage counts) is stored securely using Supabase with encrypted connections. We do not sell user data to third parties.',
  },
];

export function FAQ() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <section className="section bg-gray-950" id="faq">
      <div className="container-narrow">
        <div className="text-center mb-12">
          <p className="text-sm font-semibold text-violet-400 uppercase tracking-wider mb-3">FAQ</p>
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Frequently Asked Questions
          </h2>
        </div>

        <div className="space-y-3">
          {FAQS.map((faq, i) => (
            <div
              key={i}
              className={`rounded-2xl border transition-all duration-200 overflow-hidden ${
                open === i ? 'bg-gray-900 border-violet-500/30' : 'bg-gray-900/50 border-gray-800 hover:border-gray-700'
              }`}
            >
              <button
                onClick={() => setOpen(open === i ? null : i)}
                className="w-full flex items-center justify-between p-6 text-left"
              >
                <span className="font-semibold text-white pr-4">{faq.q}</span>
                <ChevronDown
                  className={`w-5 h-5 text-gray-400 shrink-0 transition-transform duration-200 ${
                    open === i ? 'rotate-180 text-violet-400' : ''
                  }`}
                />
              </button>
              {open === i && (
                <div className="px-6 pb-6 text-gray-400 text-sm leading-relaxed">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Schema.org FAQ structured data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'FAQPage',
              mainEntity: FAQS.map((faq) => ({
                '@type': 'Question',
                name: faq.q,
                acceptedAnswer: { '@type': 'Answer', text: faq.a },
              })),
            }),
          }}
        />
      </div>
    </section>
  );
}
